# write a program that reads in 10 numbers, then prints the sum of those
print("This program will allow you to input 10 integers and add them all.")
a = input("Input first number.")
b = input("Input second number.")
c = input("Input third number.")
d = input("Input fourth number.")
e = input("Input fifth number.")
f = input("Input sixth number.")
g = input("Input seventh number.")
h = input("Input eighth number.")
i = input("Input ninth number.")
j = input("Input tenth number.")
a = int(a)
b = int(b)
c = int(c)
d = int(d)
e = int(e)
f = int(f)
g = int(g)
h = int(h)
i = int(i)
j = int(j)
print(a + b + c + d + e + f + g + h + i + j)